const styles = {
	mainbody: {
		marginTop: 50,
		marginLeft: 24,
		marginRight: 24,
		marginBottom: 70,
		textAlign: "center",
	},
	textbuttoncta: {
		color: "#220148",
		fontSize: 18,
		textAlign: "center",
	},
	buttoncta: {
		width: 290,
		height: 60,
		backgroundColor: "none",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginLeft: 20,
		marginBottom: 24,
	},
	buttonsmallcta: {
		width: 90,
		height: 60,
		backgroundColor: "#FFFFFF",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
		color: "#4a4a4a",
	},
	buttonsmallctared: {
		width: 90,
		height: 60,
		backgroundColor: "#FF0000",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
		color: "#4a4a4a",
	},
	buttonsmallctagreen: {
		width: 90,
		height: 60,
		backgroundColor: "#03E348",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
		color: "#4a4a4a",
	},
	buttonsmallctasilver: {
		width: 90,
		height: 60,
		backgroundColor: "#E2E2E2",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
		color: "#4a4a4a",
	},
	buttonsmallctablue: {
		width: 90,
		height: 60,
		backgroundColor: "#3987C8",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
		color: "#4a4a4a",
	},
	buttonmedcta: {
		width: 135,
		height: 60,
		backgroundColor: "none",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 8,
		marginRight: 16,
	},
	buttonwrap: {
		width: 280,
		marginLeft: 32,
		flex: 1,
	    flexDirection: 'row',
	    alignItems: 'center',
	    justifyContent: 'center',
	    marginBottom: 80,
	}
}

export default styles